<?php
/**
 * Plumrocket Inc.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End-user License Agreement
 * that is available through the world-wide-web at this URL:
 * http://wiki.plumrocket.net/wiki/EULA
 * If you are unable to obtain it through the world-wide-web, please 
 * send an email to support@plumrocket.com so we can send you a copy immediately.
 *
 * @package     Plumrocket_Shipping_Tracking
 * @copyright   Copyright (c) 2014 Plumrocket Inc. (http://www.plumrocket.com)
 * @license     http://wiki.plumrocket.net/wiki/EULA  End-user License Agreement
 */
?>

<div style="background:#f7f7f7; padding:12px;">
	<form action="<?php echo $this->getUrl('*/*/*') ?>" id="tracking-number" >
	    <div class="block-content">
	        <h6>Enter Tracking number</h6>
	        <div class="input-box" >
	           <input type="text" autocapitalize="off" autocorrect="off" spellcheck="false" name="number" class="input-text required-entry">
	        </div>
	        <div class="buttons-set">
	        	<button type="submit" title="Track" class="button"><span><span>Track</span></span></button>
	        </div>
	    </div>
	</form>
</div>


<div class="buttons-set">
	<p class="back-link"><a href="<?php echo $this->getUrl('*/', array('order' => $this->getRequest()->getParam('order'))) ?>"><small>« </small><?php echo $this->__('Back') ?></a></p>
	<?php echo $this->__('Postal Services:') ?> 
	<?php if (Mage::getStoreConfig('shippingtracking/ups_api/enabled')) { ?><a href="<?php echo $this->getUrl('*/*/ups') ?>">UPS</a> | <?php } ?>
	<?php if (Mage::getStoreConfig('shippingtracking/fedex_api/enabled')) { ?><a href="<?php echo $this->getUrl('*/*/fedex') ?>">FedEx</a> | <?php } ?>
	<?php if (Mage::getStoreConfig('shippingtracking/usps_api/enabled')) { ?><a href="<?php echo $this->getUrl('*/*/usps') ?>">USPS</a> | <?php } ?>
</div>

<script type="text/javascript">
    //<![CDATA[
    var newsletterSubscriberFormDetail = new VarienForm('tracking-number');
    //]]>
</script>